### ISSUE TITLE
animation did not animate form left to right

### ISSUE THREAD

**Issue by FritzHsiao** [mac-gallagher/MultiProgressView#18]
Hi,
Thanks for this fantastic library. Everything goes well.
But if I add animate when I call setProgress, the animation will go from top left to left bottom and right. Seems like view animate from top left corner. I'm using storyboard.

I set those in viewdidload
        
       multiProgressView.trackBackgroundColor = .white
        multiProgressView.trackTitleAlignment = .left
        multiProgressView.lineCap = .round
        multiProgressView.cornerRadius = multiProgressView.frame.size.height / 2
        multiProgressView.dataSource = self
        UIView.animate(withDuration: 3.0, delay: 0.0, options: .curveLinear, animations: {
                self.multiProgressView.setProgress(section: 0, to: 0.3)
                self.multiProgressView.setProgress(section: 1, to: 0.3)
            }, completion: nil)

**Comment by mac-gallagher** [comment]
Hi @FritzHsiao! Thanks for your interest in the framework. Unfortunately, storyboards are not fully supported at the moment. I hope to integrate them in the next week or so. Stay tuned!

**Comment by mac-gallagher** [comment]
@FritzHsiao I actually realize now that your issue is not related to storyboards. If you are animating in `viewDidLoad`, the layout for the progress view has not happened yet. As a result, the initial layout is being animated together with your progress changes. 

Calling `multiProgressView.layoutSubviews()` just before your animation block should fix this. Let me know if that works!
